name: Patch Mikrotik RouterOS mmips
on:
  # push:
  #   branches: [ "main" ]
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  CUSTOM_LICENSE_PRIVATE_KEY: '86FC25CFED1A31898167F0DE205018F18C168290F5A08483BC45FDBF16994A08'
  CUSTOM_LICENSE_PUBLIC_KEY: '07F79455BA7E7C647498BDBEF234DB1E0773D23712A9F992682CB5548825C834'
  CUSTOM_NPK_SIGN_PRIVATE_KEY: '4F963FCDD7D2A4D53BAAA29C64090BC372C84387A449E0657843BDB5D06C3758'
  CUSTOM_NPK_SIGN_PUBLIC_KEY: '6593E491FF1FAFB0BF56DEB61891EFB53DCEDEB91DF3F8EA4165DB4E44B129B5'
  CUSTOM_CLOUD_PUBLIC_KEY: ${{ secrets.CUSTOM_CLOUD_PUBLIC_KEY }}
  MIKRO_LICENSE_PUBLIC_KEY: '8E1067E4305FCDC0CFBF95C10F96E5DFE8C49AEF486BD1A4E2E96C27F01E3E32'
  MIKRO_NPK_SIGN_PUBLIC_LKEY: 'C293CED638A2A33C681FC8DE98EE26C54EADC5390C2DFCE197D35C83C416CF59'
  MIKRO_CLOUD_PUBLIC_KEY: ${{ secrets.MIKRO_CLOUD_PUBLIC_KEY }}
  MIKRO_LICENCE_URL: ${{ secrets.MIKRO_LICENCE_URL }}
  CUSTOM_LICENCE_URL: ${{ secrets.CUSTOM_LICENCE_URL }}
  MIKRO_UPGRADE_URL: "upgrade.mikrotik.com"
  CUSTOM_UPGRADE_URL: ${{ secrets.CUSTOM_UPGRADE_URL }}
  MIKRO_RENEW_URL: ${{ secrets.MIKRO_RENEW_URL }}
  CUSTOM_RENEW_URL: ${{ secrets.CUSTOM_RENEW_URL }}
  MIKRO_CLOUD_URL: ${{ secrets.MIKRO_CLOUD_URL }}
  CUSTOM_CLOUD_URL: ${{ secrets.CUSTOM_CLOUD_URL }}

jobs:
  Set_BuildTime:
    runs-on: ubuntu-22.04
    outputs:
      BUILD_TIME: ${{ steps.set_buildtime.outputs.BUILD_TIME }}
    steps:
      - name: Set build time
        id: set_buildtime
        run: echo "BUILD_TIME=$(date +'%s')" >> $GITHUB_OUTPUT

  Patch_RouterOS:
    needs: Set_BuildTime
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [mmips]
        channel: [stable]
    env:
      TZ: 'Asia/Shanghai'
      LATEST_VERSION: "7.16"
      ARCH: "mmips"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Cache NetInstall ${{ env.LATEST_VERSION }}
      #if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch == 'x86'
      id: cache-netinstall
      uses: actions/cache@v4
      with:
        path: |
          netinstall.zip
          netinstall.tar.gz
        key: netinstall-${{ env.LATEST_VERSION }}

    - name: Get netinstall ${{ env.LATEST_VERSION }}
      #if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch == 'x86' && steps.cache-netinstall.outputs.cache-hit != 'true'
      run: |
        sudo wget -nv -O netinstall.zip https://download.mikrotik.com/routeros/$LATEST_VERSION/netinstall-$LATEST_VERSION.zip
        sudo wget -nv -O netinstall.tar.gz https://download.mikrotik.com/routeros/$LATEST_VERSION/netinstall-$LATEST_VERSION.tar.gz

    - name: Patch netinstall ${{ env.LATEST_VERSION }}
      #if: steps.get_latest.outputs.has_new_version == 'true' && matrix.arch == 'x86'
      run: |
        sudo unzip netinstall.zip
        sudo -E python3 patch.py netinstall netinstall.exe
        sudo zip netinstall-$LATEST_VERSION.zip ./netinstall.exe
        sudo tar -xvf netinstall.tar.gz
        sudo -E python3 patch.py netinstall netinstall-cli
        sudo tar -czvf netinstall-$LATEST_VERSION.tar.gz ./netinstall-cli

    - name: Get mikrotik-${{ env.LATEST_VERSION }}-${{ env.ARCH }}.npk
      run: |
        sudo wget -nv -O routeros-$LATEST_VERSION-${{ env.ARCH }}.npk https://download.mikrotik.com/routeros/$LATEST_VERSION/routeros-$LATEST_VERSION-${{ env.ARCH }}.npk

    - name: Patch mikrotik-${{ env.LATEST_VERSION }}-${{ env.ARCH }}.npk
      run: |
        sudo -E python3 patch.py npk routeros-$LATEST_VERSION-${{ env.ARCH }}.npk
        sudo zip routeros-$LATEST_VERSION-${{ env.ARCH }}.zip routeros-$LATEST_VERSION-${{ env.ARCH }}.npk


    - name: Create Release tag ${{ env.LATEST_VERSION }} ${{ matrix.arch }}
    
      uses: softprops/action-gh-release@v2
      with:
        name: "RouterOS ${{ env.LATEST_VERSION }} ${{ matrix.arch }}"
      
        tag_name: ${{ env.LATEST_VERSION }}${{ env.ARCH }}

        files: |
   
          routeros-${{ env.LATEST_VERSION }}-${{ env.ARCH }}.npk

          *.EFI
    



    
